interface for version 6, includes new bridge and context
takipi/takipi-sdk pull request #4
Opened 2018-07-09 16:45 UTC by GalSvirin1

2018-07-17 11:28 UTC, M-Tsur requested changes

2018-07-17 11:28 UTC, M-Tsur commented on takipi-sdk/src/main/java/com/takipi/sdk/v1/internal/impl/agent/p6/core/contexts/TakipiAgentP6Context.java
> +	protected TakipiAgentP6Context(Class<?> clazz, String methodName, String path, TakipiInternalP1Context internalContext)
This is ctor is unused and actually should extend TakipiAgentP5Context. I don't think we actually need it

2018-07-17 11:28 UTC, M-Tsur commented on takipi-sdk/src/main/java/com/takipi/sdk/v1/internal/impl/agent/p6/TakipiAgentP6ClientImpl.java
> +	public TakipiContext createInternalContext(Class<?> clazz, String methodName, String methodDesc)
why do we have createInternalContext as a public function here? is it really needed?
Other clients have createContext and nothing has to do with it being internal

2018-07-17 13:14 UTC, nivstein requested changes

2018-07-17 13:14 UTC, nivstein commented on takipi-sdk-agent-shared/src/main/java/com/takipi/sdk/v1/internal/agent/shared/p6/bridge/TakipiInternalP6AgentBridge.java
> +{
Need to keep standard Java formatting in the public repo (i.e. curly braces on same line as declaration)

2018-07-17 13:14 UTC, nivstein commented on takipi-sdk-agent-shared/src/main/java/com/takipi/sdk/v1/internal/agent/shared/p6/bridge/TakipiInternalP6AgentBridge.java
> +	public TakipiInternalP5Context createInternalContext(long contextHash);
There two methods should return a P6 context.

2018-07-17 13:14 UTC, nivstein commented on takipi-sdk/src/main/java/com/takipi/sdk/v1/internal/impl/agent/p6/TakipiAgentP6ClientImpl.java
> +{
Curly braces on line above.

2018-07-17 13:14 UTC, nivstein commented on takipi-sdk/src/main/java/com/takipi/sdk/v1/internal/impl/agent/p6/TakipiAgentP6ClientImpl.java
> +	{
Curly

2018-07-17 13:14 UTC, nivstein commented on takipi-sdk/src/main/java/com/takipi/sdk/v1/internal/impl/agent/p6/TakipiAgentP6ClientImpl.java
> +	protected TakipiAgentP6ClientImpl(String frameworkId, String clientId, TakipiOptions options, TakipiInternalP6AgentBridge bridge)
Why is this `protected` and not `private`?

2018-07-17 13:14 UTC, nivstein commented on takipi-sdk/src/main/java/com/takipi/sdk/v1/internal/impl/agent/p6/TakipiAgentP6ClientImpl.java
> +	}
Where are the `@Overrides` of the actual `createContext`s?

2018-07-17 13:14 UTC, nivstein commented on takipi-sdk/src/main/java/com/takipi/sdk/v1/internal/impl/agent/p6/core/contexts/TakipiAgentP6Context.java
> +	protected TakipiAgentP6Context(Class<?> clazz, String methodName, String path, TakipiInternalP1Context internalContext)
Agreed

2018-07-17 13:14 UTC, nivstein commented on takipi-sdk/src/main/java/com/takipi/sdk/v1/internal/impl/agent/p6/TakipiAgentP6ClientImpl.java
> +	public TakipiContext createInternalContext(Class<?> clazz, String methodName, String methodDesc)
Agreed

2018-07-22 14:17 UTC, M-Tsur approved these changes

2018-07-22 14:51 UTC, nivstein requested changes

2018-07-22 14:51 UTC, nivstein commented on takipi-sdk-agent-shared/src/main/java/com/takipi/sdk/v1/internal/agent/shared/p6/bridge/TakipiInternalP6AgentBridge.java
> +	public TakipiInternalP5Context createInternalContext(String ClassName, String methodName, String methodDesc);
`ClassName` -> `className`

2018-07-22 20:34 UTC, merged